### ISSUE TITLE
Please add a LICENSE file of some sort to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/newfirefox.mozilla.community#1]
Hi! I noticed you’re setting up a new website, and I wanted to ask you to add a LICENSE of some kind to this repository.

Typically we use a variant of Creative Commons for web content. It’s up to you what’s best here. Our general guidelines are at https://www.mozilla.org/en-US/foundation/licensing/ but they clearly note that the guidance is just that.

Without a LICENSE, this repository is “closed source”, so I try to ask for them whenever possible.

**Comment by MichaelKohler** [comment]
https://github.com/mozilla/newfirefox.mozilla.community/blob/master/LICENSE.md

Thanks for the reminder!
