### ISSUE TITLE
Short URL for download firefox

### ISSUE THREAD

**Issue by couci** [mozilla/newfirefox.mozilla.community#15]
Create short trackable URL to download firefox

**Comment by nukeador** [comment]
It seems we can't change destination long url after creation, so I would need confirmation the actual landing page we are going to point to.

**Comment by nukeador** [comment]
I'll ask Lucy to create the url pointing to /firefox/

**Comment by nukeador** [comment]
OK, this is now done:

https://mzl.la/newfirefox

**Comment by grahamperrin** [comment]
Cross reference [post 7](https://discourse.mozilla.org/t/-/21428/7?u=grahamperrin) under _Help the New Firefox! - Mozillians - Mozilla Discourse_

> … inappropriate redirection …

**Comment by nukeador** [comment]
@grahamperrin can you provide more details? I'm not quite sure where the inappropriate redirection is.

Thanks!

**Comment by MichaelKohler** [comment]
This is on mozilla.org itself, not correctly redirecting to /en-GB. Graham filed an issue for it. This has nothing to do with our short url.
