### ISSUE TITLE
Tweet from localized firefox accounts

### ISSUE THREAD

**Issue by couci** [mozilla/newfirefox.mozilla.community#2]
Ability to tweet on the launch day by using firefox localized twitter accounts like:
@firefox_es (104000) @firefox_fr (6115) @firefox_de (8371) @firefoxbrasil (134000)

**Tasks**
* [ ] Get log-in access
* [ ] Tweet on launch day

**Comment by nukeador** [comment]
mozinet has acces to Firefox_FR
_Es and _De are under marketing team

**Comment by nukeador** [comment]
cynthiapereira has access to FirefoxBrasil
