### ISSUE TITLE
Preselected language is wrong

### ISSUE THREAD

**Issue by alex-pl** [mozilla/newfirefox.mozilla.community#25]
Nice landing page! :)
I've found a small and minor bug.

German is the default locale in my browsers language settings. Therefore, the page is correctly _translated to German but "English" is selected_ in the top right corner.

This might be a little confusing to some people. Because English is the preselected item, someone who wants to see the page in English has to select another language first to be able to select English, otherwise the change-Event won't get fired.

Yep, very small, but I wanted to leave a note. Feel free to wont-fix ;)

**Comment by MichaelKohler** [comment]
Hi, good to hear from you!

You are right, the dropdown is only preselected if the lang query param is passed. I'm using l20n for this and I couldn't figure out how to get the current language for some reason.

One way would be to go through the navigator.languages (etc) properties and *hope* l20n decided for the same language, but that definitely doesn't need to be the case.

I'll further think about this before I close this ;)

Thanks for the report!
