### ISSUE TITLE
Comms plan is delivered

### ISSUE THREAD

**Issue by couci** [mozilla/newfirefox.mozilla.community#3]
We have a full communication plan before Monday the 13th

* [x] Prepare wording for the website (call for action)
* [x] Prepare e-mail for all mozillians and discourse post

**Comment by MichaelKohler** [comment]
Can you split out the wording for the website into a new issue so we can already implement that?

**Comment by couci** [comment]
Draft in here with everything: https://docs.google.com/document/d/10t0kB22Agqk0H8DpTpaDmEgQFadhs8WFLfG0lJiySQc/edit#heading=h.u60w5nqwgh8b (specific users only for now)

**Comment by couci** [comment]
everything here done, closing
