### ISSUE TITLE
add-ons not working

### ISSUE THREAD

**Issue by DarkAngie** [mozilla/newfirefox.mozilla.community#45]
After updating to the newest version of Firefox, my add-on collections no longer work. The categories are there but when I click on them it just goes to a blank page. This was one of my main reasons for using Firefox, so I would like to know if it's going to be fixed & when.

**Comment by MichaelKohler** [comment]
Please refer to support.mozilla.org.

**Comment by DarkAngie** [comment]
I'm not a programmer. I just want to know what's going on with the add-ins & if they're going to be accessible again.

**Comment by MichaelKohler** [comment]
That's why I refered you to support.mozilla.org, which is the end-user support. They can help you to get it working again. Please try again (the Add-ons website had a few problems) and if it still doesn't work, open a question on support.mozilla.org.

**Comment by DarkAngie** [comment]
I appreciate your help. It's just a run around on any of those pages, there's like no where to directly contact anyone. I think it might have fixed itself, though! Only now there's no way to add an add on into one of your collections. That's a little irritating, but not super huge. But they might want to know that. Thanks again! Abby holidays!

**Comment by cbaba20** [comment]
Hey @DarkAngie , Provide Your question here : https://support.mozilla.org/en-US/questions/new/desktop/customize . I will look into it . Or if you use twitter then ask question with @firefox and @t4templates mention, I will surely look into it and help you.

As Mike said , this is not the perfect place to drop any support related query. Hope you understand.

**Comment by DarkAngie** [comment]
Can you look into why the new version of Firefox is making Dragon NaturallySpeaking run extremely slow on some sites now? I'm quadriplegic & ventilator dependent & use Dragon NaturallySpeaking professional 13 to run my computer and everything on it, every day. Now it runs extremely slow with Firefox on one particular site that I use every day and is very important. All the other sites so far seem to work just fine still with Dragon, so I don't understand this.
